main = "index.js"
compatibility_date = "2022-05-25"

[env.dev]
name = "math-problems-dev"
workers_dev = true

[env.production]
name = "math-problems-dev"
workers_dev = false
minify = true
route = "api.math.problems/*"